### PR TITLE
fix: handling of default and star exports

### LINKED ISSUE #60: Identifier '$Completions' has already been declared
Getting error:

```ts
file:///Users/x/Developer/contra/gaia/node_modules/.pnpm/openai@4.20.0/node_modules/openai/resources/index.mjs?iitm=true:55
    let $Completions = namespace.Completions
        ^

SyntaxError: Identifier '$Completions' has already been declared
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
    at callTranslator (node:internal/modules/esm/loader:279:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:30)
```

The file contents:

```ts
// File generated from our OpenAPI spec by Stainless.
export * from "./chat/index.mjs";
export * from "./shared.mjs";
export { Audio } from "./audio/audio.mjs";
export { Beta } from "./beta/beta.mjs";
export { Completions, } from "./completions.mjs";
export { Embeddings } from "./embeddings.mjs";
```

After taking a closer look, the problem seems to be that `./chat/index.mjs` exports:

```ts
// File generated from our OpenAPI spec by Stainless.
export { Chat } from "./chat.mjs";
export { Completions, } from "./completions.mjs";
//# sourceMappingURL=index.mjs.map
```

which end up conflicting with `export { Completions, } from "./completions.mjs";`

### LINKED ISSUE #62: Import of @react-email/components breaks with import-in-the-middle
`@react-email/components` is a metapackage that re-exports the individual component libraries from `@react-email` such as `@react-email/body`, `@react-email/html`, `@react-email/tailwind`, etc.

It does this using `export * from <package>` in its index.mjs file, and the following (compiled) code for index.js:

```
module.exports = __toCommonJS(src_exports);
__reExport(src_exports, require("@react-email/body"), module.exports);
__reExport(src_exports, require("@react-email/button"), module.exports);
__reExport(src_exports, require("@react-email/column"), module.exports);
// etc for the rest of the component libraries

// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  ...require("@react-email/body"),
  ...require("@react-email/button"),
  ...require("@react-email/column"),
  // etc for the rest of the component libraries
});
```

I have created an example minimal reproduction at: https://github.com/dawnmist/import-in-the-middle-react-email-issue

## Expected Behavior

The application should be able to import any of the individual components directly from the `@react-email/components` library.

## Actual Behavior

When `import-in-the-middle` is used as an `--experimental-loader`, the import paths for the `@react-email` components get incorrectly mapped as subdirectories/siblings of the index.js/index.mjs files of the `@react-email/components` library, resulting in file not found import errors:

Yarn 4 (nodeLinker=pnpm):
```sh
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
[Error: ENOENT: no such file or directory, open '/home/username/project/node_modules/.store/@react-email-components-virtual-daf4c187d9/package/dist/@react-email/body'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/username/project/node_modules/.store/@react-email-components-virtual-daf4c187d9/package/dist/@react-email/body'
}
```

Yarn 3 (nodeLinker=pnpm):
```sh
(node:1753054) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("import-in-the-middle/hook.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
[Error: ENOENT: no such file or directory, open '/home/username/project/node_modules/.store/@react-email-components-virtual-8a501030e1/package/dist/@react-email/body'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/username/project/node_modules/.store/@react-email-components-virtual-8a501030e1/package/dist/@react-email/body'
}
```

## Steps to Reproduce the Problem

I have created an example reproduction at: https://github.com/dawnmist/import-in-the-middle-react-email-issue

  1. Clone the git repo: https://github.com/dawnmist/import-in-the-middle-react-email-issue
  2. `yarn install`
  3. `yarn build`
  3. `yarn start` - server will run without using import-in-the-middle
  4. Go to http://localhost:3000 and you should see the output "Hello world!"
  5. Stop the server
  6. `yarn start:import` - the same server will fail to run at all when using `import-in-the-middle` as an experimental-loader, throwing the error above where the @react-email/body library is instead attempted to be loaded as a subdirectory of the @react-email/components library instead of being treated as a separate npm library.

## Specifications

  - Version: import-in-the-middle version 1.7.3
  - Platform: Debian 12 linux, x86_64
  - NodeJS: 18.19.0 & 20.11.0
  - Yarn: 3.7.0 + 4.0.2

### LINKED ISSUE #68: `renamedExport` handling incorrectly adds ES module exports
The `renamedExport` handling from https://github.com/DataDog/import-in-the-middle/pull/53 incorrectly adds ES module exports. Given these three small test files:

```
% cat default-and-star-a.mjs
export default function funcA() {
  console.log('hi from a');
}
export const valueA = 'a';

% cat default-and-star-b.mjs
export * from './default-and-star-a.mjs';
export const valueB = 'b';

% cat default-and-star-main.mjs
import Hook from './index.js'
Hook((exports, name, baseDir) => {
  if (!name.includes('default-and-star')) return;
  console.log('Hooked name=%s exports:', name, exports)
})

import * as mod from './default-and-star-b.mjs'
console.log('default-and-star-b mod is:', mod)
```

When run without IITM, we expect the import of './default-and-star-b.mjs' to only have the `valueA` and `valueB` exports:

```
% node default-and-star-main.mjs
default-and-star-b mod is: [Module: null prototype] { valueA: 'a', valueB: 'b' }
```

However, when running with IITM (at tip of current "main") a `renamedExport` for the `export * from './default-and-star-a.mjs';` statement in "default-and-star-b.mjs" is incorrectly added:

```
% node --no-warnings --experimental-loader=./hook.mjs default-and-star-main.mjs
Hooked name=/Users/trentm/tm/import-in-the-middle6/default-and-star-a.mjs exports: { default: [Function: funcA], valueA: 'a' }
Hooked name=/Users/trentm/tm/import-in-the-middle6/default-and-star-b.mjs exports: { valueA: 'a', valueB: 'b', defaultAndStarA: [Function: funcA] }
default-and-star-b mod is: [Module: null prototype] {
  defaultAndStarA: [Function: funcA],
  valueA: 'a',
  valueB: 'b'
}
Hooked name=/Users/trentm/tm/import-in-the-middle6/default-and-star-main.mjs exports: {}
```

Was this possibly a misunderstanding of import behaviour while working on #53?
The #53 description says:

> I have since learned that ESM doesn't actually allow exporting default multiple times. Transitive default exports get mapped to some other name for the module that has imported them [...]

Where did the impression that "default exports get mapped to some other name for the module that has imported them" come from? Or perhaps I'm not following what the is saying.

Also the change to "hook.js" includes this comment:

```js
      // When we encounter modules that re-export all identifiers from other
      // modules, it is possible that the transitive modules export a default
      // identifier. Due to us having to merge all transitive modules into a
      // single common namespace, we need to recognize these default exports
      // and remap them to a name based on the module name. [...]
```

Is this possibly a misunderstanding as well? Taking the "default-and-star-b.mjs" example from above:

```js
export * from './default-and-star-a.mjs';
export const valueB = 'b';
```

That `export * ...` statement does *not* re-export the `default` export from "default-and-star-a.mjs".
Therefore, there should not be any need for import-in-the-middle to be adding some normalization of that property name to the hooked namespace or have a setter for it.

* * *

Assuming we agree this is a bug that should be fixed (i.e. that this was a misunderstanding),
I'll have a draft PR soonish to fix this, along with some simplifications in `getSource` and `processModule`.

### LINKED ISSUE #77: Does not handle CallExpression in ExportDefaultDeclaration node
## Expected Behavior
Works.

## Actual Behavior

```javascript
TypeError: Cannot read properties of undefined (reading 'name')
    at getEsmExports (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/lib/get-esm-exports.js:71:59)
    at getExports (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/lib/get-exports.js:80:12)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:134:23)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async processModule (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:160:20)
    at async getSource (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:269:60)
    at async load (/Users/user/code/cinemaseats/node_modules/import-in-the-middle/hook.js:335:26)
```

## Steps to Reproduce the Problem

I'm getting this after updating Sentry to 8.x. I'm not sure where exactly `import-in-the-middle` is being called from, but the gist of it is that it is crashing on [this file](https://github.com/SoftwareBrothers/adminjs/blob/master/src/frontend/components/app/sort-link.tsx) (`node_modules/adminjs/lib/frontend/components/app/sort-link.js`) because it has a function call in the export.

  1. `require('import-in-the-middle/lib/get-esm-exports')({moduleSource: 'export default parseInt("1");', defaultAs: 'sortLink'})`

## Specifications

  - Version: 1.7.4
  - Platform: macOS
  - Subsystem: ?

### PR DESCRIPTION
**Pull request by mohd-akram**
Closes #68, Closes #77, Closes #62, Closes #60

### CODE REVIEW

**Comment by mohd-akram** [comment]
I'm not sure, doesn't #86 ignore the `defaultAs` passed in? I don't think there's a reason to actually try and parse that and as I suspected it wasn't used.

**Comment by timfish** [comment]
It can't rename `export default parseInt('1')` because it doesn't have a name. It's renamed further up the import grap. 

This PR may well fix it in another way but I'd try copying the tests across the confirm that.

**Comment by mohd-akram** [comment]
Yes, clearly they do different things so either the test isn't covering it or something else. Not sure tbh. I added the tests here and they pass on my machine.

**Comment by mohd-akram** [comment]
It turns out there are other problems with the handling of default exports. I reverted the default export changes from #53 as they stemmed from a misunderstanding that `export *` includes the default export as well. The tests were therefore wrong, so I removed the wrong tests. This likely fixes other cases as well.

**Comment by timfish** [comment]
I've since opened #87, but it looks like even that can be trimmed down even more

**Comment by timfish** [comment]
`setters` as an array won't suffice because when duplicate named exports are found, all of them need to be excluded from export.

**Comment by mohd-akram** [comment]
It's a runtime error in Node.js if you do that:

```javascript
import { foo } from './entry.mjs'
         ^^^
SyntaxError: The requested module './entry.mjs' contains conflicting star exports for name 'foo'
```

where `entry.mjs` has `export * from './file1.js'` and `export * from './file2.js'` where `file1.js` == `file2.js` contents.

And if it's in the same file, it's an error as well:

```javascript
import { foo } from './file1.mjs'
import { foo } from './file2.mjs'

console.log(foo);
```

```javascript
import { foo } from './file2.mjs'
         ^^^

SyntaxError: Identifier 'foo' has already been declared
```

**Comment by mohd-akram** [comment]
Star exports were also broken. All the tests currently pass on my machine.

**Comment by timfish** [comment]
> It's a runtime error in Node.js if you do that:
> 
> ```js
> import { foo } from './entry.mjs'
>          ^^^
> SyntaxError: The requested module './entry.mjs' contains conflicting star exports for name 'foo'
> ```

Yes its a runtime error in Node, but it should also be a runtime error when using the loader hook. If you export a `foo`, there will no longer be a runtime error. That means if you find multiple named exports with the same name, they should all be excluded from the exports.

See my duplicate named exports tests here:
https://github.com/DataDog/import-in-the-middle/pull/87/files#diff-a39aaf48c07e70ea14099a7a5597088257a1b5ac55542df3a4d63e63e6546004

That's why I used this to remove duplicates:
https://github.com/DataDog/import-in-the-middle/pull/87/files#diff-e69a24a4c3746fa1ee96a78e12bb12d2dd4eb6e4cacbced2bf1f4084952681d9R119

**Comment by mohd-akram** [comment]
Adding your tests to my PR results in a runtime error as expected:

```
not ok 7 test/hook/duplicate-exports.mjs
  ---
  stdout: ''
  stderr: >-
    file:///Users/mohamed/Downloads/code/import-in-the-middle/test/fixtures/duplicate.mjs?iitm=true:21
          let $foo = _.foo
              ^

    SyntaxError: Identifier '$foo' has already been declared
        at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
        at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:18)
        at callTranslator (node:internal/modules/esm/loader:430:14)
        at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:436:30)

    Node.js v22.2.0
```

**Comment by timfish** [comment]
That's not the same runtime error, that's because the emitted iitm code contains duplicate identifiers.

You will also get that error if you do this which should not error:
`import * as lib from '/test/fixtures/duplicate.mjs'`

**Comment by mohd-akram** [comment]
Okay, it seems in Node.js there is no runtime error if you do an `import *`, but if you `import foo` then it's an error. So yeah, this should be handled.

**Comment by timfish** [comment]
Assuming all the tests pass on all node version this simplifies a lot more than my PR #87 so I'd favour this. 

As @jsumners-nr says [here](https://github.com/DataDog/import-in-the-middle/pull/87#discussion_r1618957420) though, this PR effectively reverts a PR that was supposed to fix something.

I think before we can even consider landing a PR like this with huge changes, we need to improve the tests with some real-world troublesome libraries.

File: hook.js [hunk 1]
```diff
@@ -192,69 +163,24 @@ async function processModule ({
...
- *
- * @returns {string} The normalized identifier.
- */
-function normalizeModName (name) {
-  return name
-    .split('/')
-    .pop()
-    .replace(/(.+)\.(?:js|mjs)$/, '$1')
-    .replaceAll(/(-.)/g, x => x[1].toUpperCase())
+  return { setters }
```
Comment (timfish) [inline hook.js:183]: Maybe just
```suggestion
  return setters
```

File: hook.js [hunk 2]
```diff
@@ -312,61 +238,25 @@ function createHook (meta) {
   async function getSource (url, context, parentGetSource) {
     if (hasIitm(url)) {
       const realUrl = deleteIitm(url)
-      const { imports, namespaces, setters: mapSetters } = await processModule({
+      const { setters } = await processModule({
```
Comment (timfish) [inline hook.js:241]:
```suggestion
      const setters = await processModule({
```

File: hook.js (hunk 1 above)
Comment (mohd-akram) [reply hook.js]: Thanks.

**Comment by timfish** [comment]
Looks good!

Rather than me opening another PR to add more tests, do you think it's worth adding this patch to your PR?
[import-in-the-middle-0190d24-Add tests.patch](https://github.com/DataDog/import-in-the-middle/files/15488201/import-in-the-middle-0190d24-Add.tests.patch)

The `got` test passes on `main` and this PR fixes the other 3.

**Comment by jsumners-nr** [comment]
https://github.com/newrelic/node-newrelic/issues/1920 is the issue where most of the discoveries come from. So it looks like the following should all work:

```js
import got from 'got'
typeof got.extend === 'function'
```

```js
import { defineScript } from 'redis'
typeof defineScript === 'function'
```

```js
import OpenAI from 'openai'
typeof OpenAI === 'function'
```

**Review by timfish — APPROVED** [review]

**Comment by timfish** [comment]
@mohd-akram If you update you PR description to include the following, it'll auto-close them when this gets merged:

Closes https://github.com/DataDog/import-in-the-middle/issues/68, Closes https://github.com/DataDog/import-in-the-middle/issues/77, Closes https://github.com/DataDog/import-in-the-middle/issues/62, Closes https://github.com/DataDog/import-in-the-middle/issues/60...

**Comment by mohd-akram** [comment]
@timfish Thanks, updated. There seems to be some problem with the `openai.mjs` test though, possibly an issue with imhotap. Running `imhotap --files test/hook/openai.mjs` in Node.js 16 even if it includes nothing but `import OpenAI from 'openai'` results in a `not ok` whereas `node test/hook/openai.mjs` exits with code 0 fine. Shall I remove it for now?

**Comment by timfish** [comment]
What version of Node does the `openai` test pass on?

You can limit the test version by prepending a version the test file name:
`./test/hook/v18.19-openai.mjs`

**Comment by mohd-akram** [comment]
Thanks, indeed it doesn't work before 18.19.

**Comment by mohd-akram** [comment]
Had to move the other tests too. Looks good now.

File: test/fixtures/default-class.mjs
Comment (AbhiPrasad) [inline test/fixtures/default-class.mjs:1]: Why are we removing this and `test/fixtures/snake_case.mjs`? Don't we still need to account for these as regression test cases?

Comment (mohd-akram) [reply test/fixtures/default-class.mjs:1]: The test was wrong, it was using exports that are not supposed to be there. We also added other tests that check for more things and added testing `got` directly, so the `got-alike` test can be removed altogether but it doesn't hurt to have. There's also already another `default-class.mjs`.

Comment (timfish) [reply test/fixtures/default-class.mjs:1]: This could be kept but it doesn't serve much of a purpose any more.

`snake_case.mjs` only exports a default export and was imported elsewhere with `export * from` which means it's dropped and not exported and there are multiple other places this is tested. It existed before to ensure namespaces had valid identifier names which were derived from file names.

**Review by AbhiPrasad — APPROVED** [review]
Okay seems reasonable enough to me. I tested with some fixtures in https://github.com/nodejs/node/tree/main/test/fixtures/es-modules and tried applying the patch on some sentry internal projects and nothing crashed, let's give it a try!

**Review by bengl — APPROVED** [review]
