### PR TITLE
Fix node 20 reexports

### LINKED ISSUE #29: `getExports` used for node v20, v18.19.0 doesn't handle reexports
import-in-the-middle hooking of a CommonJS module that has reexports breaks usage of that module. For example:

```
% node --version
v20.2.0

% cat foo.mjs
import { S3Client, ListBucketsCommand } from '@aws-sdk/client-s3';
console.log('hi');

% node foo.mjs
hi

% node --experimental-loader=import-in-the-middle/hook.mjs foo.mjs
(node:91931) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/trentm/tmp/iitm-node20-exports/foo.mjs:1
import { S3Client, ListBucketsCommand } from '@aws-sdk/client-s3';
                   ^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@aws-sdk/client-s3' does not provide an export named 'ListBucketsCommand'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

Node.js v20.2.0
```

## Steps to Reproduce the Problem

1. Save this "package.json":

```json
{
  "name": "iitm-node20-exports",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "@aws-sdk/client-s3": "^3.363.0",
    "import-in-the-middle": "^1.4.1"
  }
}
```

2. Save this "foo.mjs":

```js
import { S3Client, ListBucketsCommand } from '@aws-sdk/client-s3';
console.log('hi');
```

3. Run this (using node v20):

```
node --experimental-loader=import-in-the-middle/hook.mjs foo.js
```

## details

Adding this console.log to import-in-the-middle/lib/get-exports.js:

```js
  if (format === 'commonjs') {
    console.log('XXX IITM getCjsExports of url %s\n-- source --\n%s\n-- parsed --\n%o\n--', url, source, getCjsExports(source))
    return addDefault(getCjsExports(source).exports)
  }
```

<details>
<summary>and re-running:</summary>

```
% node --experimental-loader=import-in-the-middle/hook.mjs foo.mjs
(node:96950) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
XXX IITM getCjsExports of url file:///Users/trentm/tmp/iitm-node20-exports/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
-- source --
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.S3ServiceException = void 0;
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./S3Client"), exports);
tslib_1.__exportStar(require("./S3"), exports);
tslib_1.__exportStar(require("./commands"), exports);
tslib_1.__exportStar(require("./pagination"), exports);
tslib_1.__exportStar(require("./waiters"), exports);
tslib_1.__exportStar(require("./models"), exports);
var S3ServiceException_1 = require("./models/S3ServiceException");
Object.defineProperty(exports, "S3ServiceException", { enumerable: true, get: function () { return S3ServiceException_1.S3ServiceException; } });

-- parsed --
{
  exports: [ '__esModule', 'S3ServiceException', [length]: 2 ],
  reexports: [
    './S3Client',
    './S3',
    './commands',
    './pagination',
    './waiters',
    './models',
    [length]: 6
  ]
}
--
XXX IITM getCjsExports of url file:///Users/trentm/tmp/iitm-node20-exports/node_modules/@aws-sdk/client-s3/dist-cjs/index.js
-- source --
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.S3ServiceException = void 0;
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./S3Client"), exports);
tslib_1.__exportStar(require("./S3"), exports);
tslib_1.__exportStar(require("./commands"), exports);
tslib_1.__exportStar(require("./pagination"), exports);
tslib_1.__exportStar(require("./waiters"), exports);
tslib_1.__exportStar(require("./models"), exports);
var S3ServiceException_1 = require("./models/S3ServiceException");
Object.defineProperty(exports, "S3ServiceException", { enumerable: true, get: function () { return S3ServiceException_1.S3ServiceException; } });

-- parsed --
{
  exports: [ '__esModule', 'S3ServiceException', [length]: 2 ],
  reexports: [
    './S3Client',
    './S3',
    './commands',
    './pagination',
    './waiters',
    './models',
    [length]: 6
  ]
}
--
file:///Users/trentm/tmp/iitm-node20-exports/foo.mjs:1
import { S3Client, ListBucketsCommand } from '@aws-sdk/client-s3';
                   ^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@aws-sdk/client-s3' does not provide an export named 'ListBucketsCommand'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

Node.js v20.2.0
```

</details>

That shows the "reexports" I'm referring to.

I was kind of surprised that `cjs-module-lexer` recognized `tslib_1.__exportStar(require("./S3Client"), exports);` and similar as a "reexport". Does it have particular smarts about `tslib` or is it parsing and/or executing tslib?

Does import-in-the-middle want/need to get into recursively handling these "reexports"?

### PR DESCRIPTION
**Pull request by luxaritas**
Resolves #29

### CODE REVIEW

**Comment by tlhunter** [comment]
@luxaritas I see this is a draft... Is it ready to go?

**Comment by luxaritas** [comment]
Hey @tlhunter - main reason I left it as a draft is because I'm not confident that my approach here is "correct" - particularly how I'm handling path resolution seems hacky. That said I don't have any pending work on it, really just waiting for input, so I'll mark it as ready

File: lib/get-exports.js [hunk 1]
```diff
@@ -3,12 +3,26 @@
...
 function addDefault(arr) {
   return Array.from(new Set(['default', ...arr]))
 }
 
+async function getFullCjsExports(url, context, parentLoad, source) {
+  const ex = getCjsExports(source)
+  return Array.from(new Set([
+    ...addDefault(ex.exports),
+    ...(await Promise.all(ex.reexports.map(re => getExports(
+	    re.startsWith('./') || re.startsWith('../')
```
Comment (trentm) [inline lib/get-exports.js:17]: Possibly this should consider Windows `\\` dir separators, if on Windows? I'm not sure how important that is, and it could be done later.

**Review by trentm — CHANGES_REQUESTED** [review]
Thank you for implementing this!

I found a problem with circular imports that re-export. The current implementation will go into an infinite loop. This patch includes a test case for that and a proposed fix:
https://gist.github.com/trentm/aa10ec6c34a473aa64a2e717b931742c

@luxaritas Would you be willing to add that to your branch?

**Comment by luxaritas** [comment]
@trentm Thanks for the patch - looks reasonable to me so I've applied it. (I've marked you as a commit coauthor using git metadata from a recent GitHub commit of yours, let me know if that should be something else!)

File: lib/get-exports.js (hunk 1 above)
Comment (luxaritas) [reply lib/get-exports.js]: To be honest the entire path handling here felt hacky when I wrote it, and I'm not sure if this is the best way to do it, though I didn't immediately come up with a better option. :)

As far as windows dir separators - I suppose? I think I initially thought cjs-module-lexer would normalize this, but in retrospect that's probably not correct. This also made me realize that importing `.` or `..` would currently not be handled correctly either - I'll fix that up

**Comment by jsumners-nr** [comment]
If I'm not mistaken, this is solved by #43.

**Comment by pichlermarc** [comment]
> If I'm not mistaken, this is solved by #43.

Hmm, I I've tried the fix from #43 (released in 1.7.2) and I think it does not cover the case of CJS re-exports.

**Comment by jsumners-nr** [comment]
> > If I'm not mistaken, this is solved by #43.
> 
> Hmm, I I've tried the fix from #43 (released in 1.7.2) and I think it does not cover the case of CJS re-exports.

Drat!

**Comment by trentm** [comment]
This is just speculation, based on commit bb038e9 of this PR handling a circular imports issue: I wonder if *this* PR would also have resolved https://github.com/DataDog/import-in-the-middle/issues/31
I haven't yet had a chance to understand what #43 is doing.

**Review by bengl — APPROVED** [review]

**Comment by trentm** [comment]
Woot. Thanks very much.
