### PR TITLE
fix: CommonJs bare specifier resolution

### LINKED ISSUE #95: `getFullCjsExports` does not resolve re-exports from external dependencies
This had been fixed for ESM but not for CJS.

The following code should result in a default export
`test.cjs`
```ts
module.exports = require('util').deprecate;
```

Instead it results in the following error:
```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: ENOENT: no such file or directory, open '/Users/tim/Documents/Repositories/import-in-the-middle/test/check-exports/util'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at getExports (/Users/tim/Documents/Repositories/import-in-the-middle/lib/get-exports.js:69:17)
    at async Promise.all (index 0)
    at async getFullCjsExports (/Users/tim/Documents/Repositories/import-in-the-middle/lib/get-exports.js:23:9)
    at async processModule (/Users/tim/Documents/Repositories/import-in-the-middle/hook.js:131:23)
    at async getSource (/Users/tim/Documents/Repositories/import-in-the-middle/hook.js:249:23)
    at async load (/Users/tim/Documents/Repositories/import-in-the-middle/hook.js:280:26)
    at async nextLoad (node:internal/modules/esm/hooks:833:22)
    at async Hooks.load (node:internal/modules/esm/hooks:416:20) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tim/Documents/Repositories/import-in-the-middle/test/check-exports/util'
}
```

I think this is due to this code which doesn't support resolving bare specifiers or node built-ins?
https://github.com/DataDog/import-in-the-middle/blob/a8da141be1e0fe802cea9bdb83d39a61c3aea7f7/lib/get-exports.js#L20-L30

### PR DESCRIPTION
**Pull request by timfish**
Closes #95

I've also made the `getExports` functions return `Set<string>` instead of `string[]` as this saves a load of unnecessary allocations. 

I've also run this through the additional module tests in #93 and get the same results.

### CODE REVIEW

File: lib/get-exports.js [hunk 1]
```diff
@@ -1,36 +1,46 @@
...
-      parentLoad
-    )))).flat()
-  ]))
+  try {
+    const result = parseCjs(source)
+    const full = addDefault(result.exports)
 
-  urlsBeingProcessed.delete(url)
-  return full
+    for (const re of result.reexports) {
```
Comment (AbhiPrasad) [inline lib/get-exports.js:26]: I think we still should `Promise.all` because of the `await getExports` call.

File: lib/get-exports.js [hunk 2]
```diff
@@ -57,23 +67,23 @@ async function getExports (url, context, parentLoad) {
...
-    return addDefault(Object.keys(require(url)))
-  }
-
   if (!source) {
-    // Sometimes source is retrieved by parentLoad, sometimes it isn't.
-    source = fs.readFileSync(fileURLToPath(url), 'utf8')
+    if (format === 'builtin') {
+      // Builtins don't give us the source property, so we're stuck
+      // just requiring it to get the exports.
+      return addDefault(Object.keys(require(url)))
```
Comment (AbhiPrasad) [inline lib/get-exports.js:74]: should we cache this? I guess should we cache the `fs.readFileSync` as well?

**Review by AbhiPrasad — APPROVED** [review]
seems reasonable to me!

File: lib/get-exports.js (hunk 2 above)
Comment (timfish) [reply lib/get-exports.js:74]: Possibly, but this is only for built-ins. I'll benchmark it to see how slow it is.

I don't think we should cache the `readFileSync` calls because most files will only be hit once and we'll be left hanging onto the memory.

Comment (timfish) [reply lib/get-exports.js:74]: In all the tests this specific require is only hit once so it's quite a niche code path.

There's another `Object.keys(require(id))` further down which is hit for every build-in module load from CJS code and the maximum I see is for `node:child_process` at about 1ms. These are probably worth caching because there's a limited number of possible built-ins.

**Review by bengl — APPROVED** [review]
